Change data directory.

diff --git a/bred b/bred
--- a/bred
+++ b/bred
@@ -43,7 +43,7 @@ showhelp() {
   echo   "  -o: output file, default = stdout"
   echo   "  -e: error file, default = stderr"
   echo   "  -r: userfunc function, default = identity"
-  echo   "  -t: tmp dir to use, default = /tmp"
+  echo   "  -t: tmp dir to use, default = $HOME/.bred"
   echo   "  -S: memory to use for 'S'ort, default = 256M"
   echo   "  -s: column to 's'ort(s) on reduce (and following merge). , default is equal to -c "
   echo   "  -T: option given to sor'T'(s) on reduce (and following merge), default is nothing"
@@ -58,8 +58,8 @@ showhelp() {
 #   
 # out
 #   jobid    "${OPTARG:-$(uuid)}"
-#   jobpath  "${tmp_dir:-/tmp}/br_job_${jobid}}"
-#   nodepath "${tmp_dir:-/tmp}/br_node_${jobid}}"
+#   jobpath  "${tmp_dir:-$HOME/.bred}/jm/${job_idx}/job"
+#   nodepath "${tmp_dir:-$HOME/.bred}/jm/${job_idx}/nodes/${host_idx}"
 # local
 bred_parseopt() {
   LC_ALL=${LC_ALL:-""}
@@ -73,7 +73,7 @@ bred_parseopt() {
   input=
   output=
   error=
-  tmp_dir=/tmp
+  tmp_dir=${HOME}/.bred
   sort_mem=256M
   sort_column=
   sort_on_out="yes"
@@ -84,7 +84,7 @@ bred_parseopt() {
     case "$name" in
       m)  hosts=$OPTARG;;
       p)  baseport=$OPTARG;;
-      j)  job_idx=$OPTARG;;
+      j)  job_idx=$OPTARG;; # Will be ignored.
       M)  mode=$OPTARG;;
       I)  interpreter=$OPTARG;;
       c)  mapcolumn=$OPTARG;;
@@ -104,10 +104,10 @@ bred_parseopt() {
   done
   # job_idx
   local _nextid
-  local _jid_dir=/tmp/bred/jid
+  local _jid_dir="${tmp_dir}/jm"
   job_idx="$(_nextid=$(echo $(($(ls ${_jid_dir}| sort -n -r  | head --lines=1) + 1))) \
            && mkdir ${_jid_dir}/${_nextid} && echo ${_nextid} || echo -1)"
-
+  echo "$$" > "${_jid_dir}/${job_idx}/pid"
 
   hosts=$(bred_load_brhosts "$hosts")
   sort_column=${sort_column:-$mapcolumn}
@@ -121,7 +121,7 @@ bred_parseopt() {
       usage $0
       ;;
   esac
-  jobid=${jobid:-"`uuidgen`"}
+  job_id=${jobid:-"`uuidgen`"}
 }
 
 # * in
@@ -136,8 +136,8 @@ bred_compose_task() {
     # mode: 'map', 'reduce', 'compat'
     local mode=$1
     local host_idx=$2
-    local usercode_errlog="${3}/err_${host_idx}-usercode.err"
-    local sorter_errolog="${3}/err_${host_idx}-sorter.err"
+    local usercode_errlog="${3}/err-usercode.log"
+    local sorter_errolog="${3}/err-sorter.log"
 
     sorter="2>$sorter_errolog"
     if [ "$sort_on_out" == "yes" ] ; then
@@ -148,9 +148,9 @@ bred_compose_task() {
     local envvars=
     local _namenode=$(hostname)
     local _hosts="${hosts}"
-    local _bredfs_init=$(bredfs_compose_init '/tmp/bredfs' | base64 -w 0)
-    local _bredfs_write=$(bredfs_compose_write "${_namenode}" '/tmp/bredfs' | base64 -w 0)
-    local _bredfs_read=$(bredfs_compose_read '/tmp/bredfs' "${host_idx:-'-'}" "${_hosts}" | base64 -w 0)
+    local _bredfs_init=$(bredfs_compose_init "/${tmp_dir}/fs" | base64 -w 0)
+    local _bredfs_write=$(bredfs_compose_write "${_namenode}" '/${tmp_dir}/fs' | base64 -w 0)
+    local _bredfs_read=$(bredfs_compose_read "${tmp_dir}/fs" "${host_idx:-'-'}" "${_hosts}" | base64 -w 0)
     envvars="BRED_PART_ID=\"$host_idx\" BRED_KEYINDEX=\"$mapcolumn\" BRED_INTERPRETER=\"$interpreter\""
     envvars="${envvars} BRED_USERCODE='$userfunc'"
     envvars="${envvars} BREDFS_INIT='${_bredfs_init}'"
@@ -270,64 +270,64 @@ bred_compose_task() {
 # * local
 #   host, pid, envvars, port_in, port_out, host_idx, out_files, in_filed, input, num_hosts
 bred_executetask() {
-    AWK="/usr/bin/awk"
-    # okay let's get started!  first we need a name for our job
-    local jobpath="$tmp_dir/br_job_$jobid"
-    local nodepath="$tmp_dir/br_node_$jobid"
-    local num_hosts=$(($(echo "$hosts" | wc -w)))
-    local port_in=$(($base_port + $num_hosts * $job_idx * 2))
-    local port_out=$(($port_in + 1))
-    local host_idx=0
-    local out_files=
-    local in_files=
-
-    # now, for each host, set up in and out fifos (and a netcat for each), and ssh to each host to set up workers listening on netcat
-    mkdir -p ${jobpath}/{in,out}
-    for host in ${hosts}; do
-        ####
-        # set up communication path
-        # 1) master side
-        #    our named pipes
-        mkfifo ${jobpath}/{in,out}/${host_idx}
-        # 2) slave size
-        ssh -n "$host" "mkdir -p ${nodepath}"
-        #    let's start the remote 'nc' listener and get the pid of it
-        local pid=$(ssh -n "$host" "nc -l -p $port_out >$nodepath/in_$host_idx 2>/dev/null </dev/null & jobs -l" | awk {'print $2'})
-
-        ####
-        # start task process on remote side and connect to it to the listener
-        # 1) compose 'task' component based on execution mode (map, reduce, or compat)
-        bred_compose_task "$mode" "$host_idx" "$nodepath"
-        # 2) start the task.
-        ssh "$host" -n "\
-            tail -s0.1 -f --pid=$pid $nodepath/in_$host_idx 2>/dev/null </dev/null \
+  AWK="/usr/bin/awk"
+  # okay let's get started!  first we need a name for our job
+  local jobpath="$tmp_dir/jm/${job_idx}/job"
+  local nodepath="$tmp_dir/jm/${job_idx}/nodes"
+  local num_hosts=$(($(echo "$hosts" | wc -w)))
+  local port_in=$(($base_port + $num_hosts * $job_idx * 2))
+  local port_out=$(($port_in + 1))
+  local host_idx=0
+  local out_files=
+  local in_files=
+  
+  # now, for each host, set up in and out fifos (and a netcat for each), and ssh to each host to set up workers listening on netcat
+  mkdir -p ${jobpath}/{in,out}
+  for host in ${hosts}; do
+    ####
+    # set up communication path
+    # 1) master side
+    #    our named pipes
+    mkfifo ${jobpath}/{in,out}/${host_idx}
+    # 2) slave size
+    ssh -n "$host" "mkdir -p ${nodepath}/${host_idx}"
+    #    let's start the remote 'nc' listener and get the pid of it
+    local pid=$(ssh -n "$host" "nc -l -p $port_out >${nodepath}/${host_idx}/in 2>/dev/null </dev/null & jobs -l" | awk {'print $2'})
+    
+    ####
+    # start task process on remote side and connect to it to the listener
+    # 1) compose 'task' component based on execution mode (map, reduce, or compat)
+    bred_compose_task "$mode" "$host_idx" "${nodepath}"
+    # 2) start the task.
+    ssh "$host" -n "\
+            tail -s0.1 -f --pid=$pid ${nodepath}/${host_idx}/in 2>/dev/null </dev/null \
                     $task \
                     | nc -q0 -l -p $port_in >&/dev/null &"
-	
-        ####
-        # Connect the task to the local forwarder of master side's
-        # our local forwarders
-        nc "$host" "$port_in" >"$jobpath/in/$host_idx" &
-        nc -q0 "$host" "$port_out" <"$jobpath/out/$host_idx" &
-        # our vars
-        out_files="$out_files $jobpath/out/$host_idx"
-        in_files="$in_files $jobpath/in/$host_idx"
-        port_in=$(($port_in + 2))
-        port_out=$(($port_in + 1))
-        host_idx=$(($host_idx + 1))
-    done
     
-    ####    
-    # okay, time to map
-    if which brp >/dev/null; then
-        eval "${input:+pv $input |} brp - $((${mapcolumn} - 1)) ${out_files}"
-    else
-        ####
-        # use awk if we don't have 'brp'
-        # we're taking advantage of a special property that awk leaves its file handles open until its done
-        # i think this is universal
-        # we're also sending a zero length string to all the handles at the end, in case some pipe got no love
-        eval "${input:+pv $input |} awk '{
+    ####
+    # Connect the task to the local forwarder of master side's
+    # our local forwarders
+    nc "$host" "$port_in" >"$jobpath/in/$host_idx" &
+    nc -q0 "$host" "$port_out" <"$jobpath/out/$host_idx" &
+    # our vars
+    out_files="$out_files $jobpath/out/$host_idx"
+    in_files="$in_files $jobpath/in/$host_idx"
+    port_in=$(($port_in + 2))
+    port_out=$(($port_in + 1))
+    host_idx=$(($host_idx + 1))
+  done
+  
+  ####    
+  # okay, time to map
+  if which brp >/dev/null; then
+    eval "${input:+pv $input |} brp - $((${mapcolumn} - 1)) ${out_files}"
+  else
+    ####
+    # use awk if we don't have 'brp'
+    # we're taking advantage of a special property that awk leaves its file handles open until its done
+    # i think this is universal
+    # we're also sending a zero length string to all the handles at the end, in case some pipe got no love
+    eval "${input:+pv $input |} awk '{
             srand(\$$mapcolumn);
             print \$0 >>\"$jobpath/out/\"int(rand() * $host_idx);
         }
@@ -335,44 +335,45 @@ bred_executetask() {
             for (i = 0; i != $host_idx; ++i)
             printf \"\" >>\"$jobpath/out/\"i;
         }'"
-    fi
-
-    ####    
-    # save it somewhere
-    # use sort -m. 
-    # (dakusui: abolished brm to simplify the software since i couldn't convince myself there is a big performance gain)
-    # sort -m creates tmp files if too many input files are specified
-    # brm doesn't do this
-    if [ ${sort_on_out} == "yes" ] ; then
-        eval "sort -k${sort_column},${sort_column} -m ${in_files} ${sort_opt} ${output:+| pv >$output}"
+  fi
+  
+  ####    
+  # save it somewhere
+  # use sort -m. 
+  # (dakusui: abolished brm to simplify the software since i couldn't convince myself there is a big performance gain)
+  # sort -m creates tmp files if too many input files are specified
+  # brm doesn't do this
+  if [ ${sort_on_out} == "yes" ] ; then
+    eval "sort -k${sort_column},${sort_column} -m ${in_files} ${sort_opt} ${output:+| pv >$output}"
+  else
+    eval "cat ${in_files} ${output:+| pv >$output}"
+  fi
+  
+  ####
+  # save errors somewhere
+  local i=0;
+  for host in ${hosts}; do
+    local cmd='for i in $(ls '${nodepath}'/'${i}'/err*); do echo '${i}' $(basename $i); nl -w 1 -s " " $i; echo '${i}' ----; done'
+    if [ -n "$error" ]; then
+      ssh "$host" "$cmd" >>"$error"
     else
-        eval "cat ${in_files} ${output:+| pv >$output}"
+      # By default, redirect stdouts of ssh commands to stderr because the files are originally stderr.
+      ssh "$host" "$cmd" 1>&2
     fi
-    
-    ####
-    # save errors somewhere
-    local i=0;
-    for host in ${hosts}; do
-        local cmd='for i in $(ls '${nodepath}'/err_'${i}'*); do echo '${i}' $(basename $i); nl -w 1 -s " " $i; echo '${i}' ----; done'
-        if [ -n "$error" ]; then
-            ssh "$host" "$cmd" >>"$error"
-        else
-            # By default, redirect stdouts of ssh commands to stderr because the files are originally stderr.
-            ssh "$host" "$cmd" 1>&2
-        fi
-        i=$(($i + 1))
-    done
-
-    ####    
-    # finally, clean up after ourselves
-    # rm -rf "$jobpath"
-    # for host in ${hosts}; do
-    #    ssh "$host" "rm -fr ${nodepath:?'node path isn't set''}"
-    # done
-    
-    ####    
-    # TODO: is there a safe way to kill subprocesses upon fail?
-    # this seems to work: /bin/kill -- -$$
+    i=$(($i + 1))
+  done
+  
+  ####    
+  # finally, clean up after ourselves
+  rm -rf "${jobpath:?something goes wrong!}"
+  for host in ${hosts}; do
+    ssh "$host" "rm -fr ${nodepath:?'node path isn't set''}"
+  done
+  rm -fr "${tmp_dir:?something goes wrong!}/jm/${job_idx:?something goes wrong!}"
+  
+  ####    
+  # TODO: is there a safe way to kill subprocesses upon fail?
+  # this seems to work: /bin/kill -- -$$
 }
 
 . "$(dirname $0)/bred-core"
