conf file support (2nd commit)

diff --git a/bred-core b/bred-core
--- a/bred-core
+++ b/bred-core
@@ -51,9 +51,10 @@ unpack_arr() {
 # Parameters:
 # - $1: A base directory of the local stroage of poorman's DFS
 bredfs_compose_init() {
-  local _fsbase=${1}
-  local _s='echo "" | bred -r "mkdir -p %s/\${BRED_PARTID}/$(dirname ${STORE}) ; truncate -s 0 %s/\${BRED_PARTID}/$(dirname ${STORE})/$(basename ${STORE})" -T "-n" -c 1'
-  printf "${_s}" "${_fsbase}" "${_fsbase}"
+  local _conffile="${1}"
+  local _fsbase="${2:?ERR:_conffile=${_conffile}}"
+  local _s='echo "" | bred -C "%s" -r "mkdir -p %s/\${BRED_PARTID}/$(dirname ${STORE}) ; truncate -s 0 %s/\${BRED_PARTID}/$(dirname ${STORE})/$(basename ${STORE})" -T "-n" -c 1'
+  printf "${_s}" "${_conffile}" "${_fsbase}" "${_fsbase}"
 }
 
 ####
@@ -64,10 +65,11 @@ bredfs_compose_init() {
 # - $2: A base directory of the local stroage of poorman's DFS
 bredfs_compose_write() {
   # nl -w 1 -b a ~/Documents/FSM.md | bred -r 'cat > /tmp/bredfs/${BRED_WORKER_IDX}/work/FSM.md' -T '-n' -c 1 >& /dev/null
-  local _namenode=(${1})
-  local _fsbase=${2}
+  local _conffile="${1}"
+  local _fsbase=${2:?"ERR:_fsbase was not given"}
+  local _namenode=(${3:?"ERR:_conffile=${_conffile}, _namenode=${_namenode}"})
 
-  local _f='nl -w 1 -b a -s " " ${APPEND} | ssh -o SendEnv=TO localhost "bred -r '\''cat >> '${_fsbase}'/\${BRED_PARTID}/${TO}'\'' -T '\''-n'\'' -c '\''1'\''"'
+  local _f='nl -w 1 -b a -s " " ${APPEND} | ssh -o SendEnv=TO localhost "bred -C '"${_conffile}"'-r '\''cat >> '${_fsbase}'/\${BRED_PARTID}/${TO}'\'' -T '\''-n'\'' -c '\''1'\''"'
   printf "${_f}" ${_namenode} ${_fsbase} '${TO}'
 }
 
@@ -99,28 +101,37 @@ bredfs_compose_read() {
 ####
 # Exports BREDFS environment variables
 bredfs_exportenv() {
-  local _conffile="${1:~/.bred/bred.conf}"
-  local _host_idx="${2:-}"
-  local _hosts=$(bred_load_brhosts ${2:-""})
-  local _namenode="${_hosts[0]}"
-  local _fsbase="${3:-${HOME}/.bred/fs}"
-  ####
-  # Configurable parameters and their default values
-  baseport=8192
-  hosts=(localhost localhost localhost localhost)
-  workdir=/tmp/bred
-  fsdir=${workdir}/fs
-  jmdir=${workdir}/jm
-  sorttmpdir=${workdir}/tmp
-  sortmem[localhost]=32M
-  defaultsortmem=256K
+  local _host_idx="${1:?'Missing partition id (host idx)'}"
+  local _conffile="${2:?'Missing conf file'}"
   ####
   # Load per user config
-  if [ -r "~/.bred/bred.conf" ]; then
-    source "~/.bred/bred.conf"
+  declare -A sortmem
+  if [ -r "${_conffile}" ]; then
+    ####
+    # Configurable parameters and their default values
+    # Example
+    #   baseport=10000
+    #   hosts=(localhost localhost localhost localhost)
+    #   namenode=${hosts[0]}
+    #   workdir=/tmp/bred
+    #   fsdir=${workdir}/fs
+    #   jmdir=${workdir}/jm
+    #   sorttmpdir=${workdir}/tmp
+    #   sortmem[localhost]=32M
+    #   defaultsortmem=256K
+    source "${_conffile}"
+  else
+    echo "Config file '${_conffile}' was not found.($1)($2)" >& 2
+    exit 1
   fi
-  export BREDFS_INIT=$(bredfs_compose_init "${_fsbase}" | base64 -w 0)
-  export BREDFS_WRITE=$(bredfs_compose_write "${_namenode}" "${_fsbase}" | base64 -w 0)
+  local _hosts="${hosts[@]}"
+  local _namenode="${namenode}"
+  local _fsbase="${fsdir}"
+
+  echo "_conffile=${_conffile}" >& 2
+  echo "_fsbase=${_fsbase}" >& 2
+  export BREDFS_INIT=$(bredfs_compose_init "${_conffile}" "${_fsbase}" | base64 -w 0)
+  export BREDFS_WRITE=$(bredfs_compose_write "${_conffile}" "${_fsbase}" "${_namenode}" | base64 -w 0)
   export BREDFS_READ=$(bredfs_compose_read "${_fsbase}" "${_host_idx:-'-'}" "${_hosts}" | base64 -w 0)
 }
 
@@ -155,4 +166,6 @@ bredfs() {
 }
 
 # Export the environment variables
-bredfs_exportenv
+prog=${0}
+debug ": BRED_CONF=${BRED_CONF}"
+bredfs_exportenv "${BRED_PARTID:-'-'}" "${BRED_CONF:-${HOME}/.bred/bred.conf}"
