Implement a feature to handle error written by usercodes. Re-implement a feature to pass option to sort commands used in merge process following map/reduce user code execution.

diff --git a/bred b/bred
--- a/bred
+++ b/bred
@@ -23,13 +23,13 @@
 
 usage() {
     local prog="`basename $1`"
-    echo "Usage: $prog [-m host1 [host2...]] [-c column] [-r userfunc] [-i input] [-o output]"
+    echo "Usage: $prog [-m host1 [host2...]] [-c column] [-r userfunc] [-i input] [-o output] [-e error]"
     echo "       $prog -h for help."
     exit 2
 }
 
 showhelp() {
-    echo "Usage: `basename $1`: [-m host1 [host2...]] [-c column] [-r userfunc] [-i input] [-o output]"
+    echo "Usage: `basename $1`: [-m host1 [host2...]] [-c column] [-r userfunc] [-i input] [-o output] [-e error]"
     echo   "bashreduce.  Map an input file to many hosts, sort/reduce, merge"
     echo   "  -m: hosts to use, can repeat hosts for multiple cores"
     echo   "      default hosts from ~/.br.hosts or /etc/br.hosts"
@@ -39,13 +39,15 @@ showhelp() {
     echo   "  -j: job index, default = 0"
     echo   "  -c: column to partition, default = 1 (1-based)"
     echo   "  -i: input file, default = stdin"
-    echo   "  -r: userfunc function, default = identity"
     echo   "  -o: output file, default = stdout"
+    echo   "  -e: error file, default = stderr"
+    echo   "  -r: userfunc function, default = identity"
     echo   "  -t: tmp dir to use, default = /tmp"
-    echo   "  -l: error log file, default = /dev/null"
-    echo   "  -S: memory to use for sort, default = 256M"
-    echo   "  -s: column to sort on reduce. 'sort' command, default is equal to -c "
+    echo   "  -S: memory to use for 'S'ort, default = 256M"
+    echo   "  -s: column to 's'ort(s) on reduce (and following merge). , default is equal to -c "
+    echo   "  -T: option given to sor'T'(s) on reduce (and following merge), default is nothing"
     echo   "  -O: perform sort on output, ignored in 'compat' mode., default = yes"
+    echo   "  -v: verbose mode. default = no"
     echo   "  -h: this help message"
     exit 2
 } 
@@ -71,13 +73,15 @@ bashr_parseopt() {
     userfunc=
     input=
     output=
+    error=
     tmp_dir=/tmp
     sort_mem=256M
     sort_column=
-    sort_on_out=yes
-    errlog='/dev/null'
-    
-    while getopts "m:p:j:M:I:c:r:i:o:t:S:s:O:l:h" name; do
+    sort_on_out="yes"
+    sort_opt=
+    verbose="no"
+     
+    while getopts "m:p:j:M:I:c:r:i:o:e:t:S:s:T:O:v:h" name; do
 	case $name in
 	    m)  hosts=$OPTARG;;
 	    p)  baseport=$OPTARG;;
@@ -88,11 +92,13 @@ bashr_parseopt() {
 	    r)  userfunc=$OPTARG;;
 	    i)  input=$OPTARG;;
 	    o)  output=$OPTARG;;
+	    e)  error=$OPTARG;;
 	    t)  tmp_dir=$OPTARG;;
 	    S)  sort_mem=$OPTARG;;
 	    s)  sort_column=$OPTARG;;
             O)  sort_on_out=$OPTARG;;
-	    l)  errlog=$OPTARG;;
+            T)  sort_opt=$OPTARG;;
+            v)  verbose="yes";;
 	    h)  showhelp $0;;
 	    [?])  usage $0;;
 	esac
@@ -119,7 +125,8 @@ bashr_parseopt() {
 
 # * in
 #   mode (param[1])
-#   host_idx (param[1])
+#   host_idx (param[2])
+#   nodepath (param[3])
 #   LC_ALL (from env)
 #   mapcolumn (from opt)
 #   interpreter (from opt)
@@ -134,9 +141,12 @@ bashr_parseopt() {
 #   envvars
 bashr_compose_task() {
     # mode: 'map', 'reduce', 'compat'
-    mode=$1
-    host_idx=$2
-    sorter="LC_ALL='$LC_ALL' sort -S$sort_mem -T$tmp_dir -k$sort_column,$sort_column 2>/dev/null"
+    local mode=$1
+    local host_idx=$2
+    local usercode_errlog="${3}/err_${host_idx}-usercode.err"
+    local sorter_errolog="${3}/err_${host_idx}-sorter.err"
+    
+    sorter="LC_ALL='$LC_ALL' sort -S$sort_mem -T$tmp_dir -k$sort_column,$sort_column $sort_opt  2>$sorter_errolog"
     local usercode=
     local envvars="MAPCOLUMN=$mapcolumn INTERPRETER='$interpreter' USERFUNC='$userfunc' HOST_IDX='$host_idx'"
     case $mode in 
@@ -177,12 +187,12 @@ bashr_compose_task() {
                     close(cmd);
                 }
             }'
-            task="$envvars awk '$usercode' | $sorter"
+            task="$envvars awk '$usercode' 2> $usercode_errlog | $sorter"
             ;;
 	compat)
 	    if [ -n "$userfunc" ]; then
 	    # if we have a userfunc, add the pipe explicitly
-		usercode="| $userfunc 2> $errlog"
+		usercode="| $userfunc 2> $usercode_errlog"
             else
                 usercode=""
 	    fi
@@ -251,7 +261,7 @@ bashr_executetask() {
         ####
         # start task process on remote side and connect to it to the listener
         # 1) compose 'task' component based on execution mode (map, reduce, or compat)
-	bashr_compose_task "$mode" "$host_idx"
+	bashr_compose_task "$mode" "$host_idx" "$nodepath"
         # 2) start the task.
 	ssh $host -n \
 	    "tail -s0.1 -f --pid=$pid $nodepath/in_$host_idx 2>/dev/null </dev/null \
@@ -298,16 +308,28 @@ bashr_executetask() {
     # sort -m creates tmp files if too many input files are specified
     # brm doesn't do this
     if [ $sort_on_out == "yes" ] ; then
-	eval "sort -k$sort_column,$sort_column -m $in_files ${output:+| pv >$output}"
+	eval "sort -k$sort_column,$sort_column -m $in_files $sort_opt ${output:+| pv >$output}"
     else
 	eval "cat $in_files ${output:+| pv >$output}"
     fi
     
+    ####
+    # save errors somewhere
+    for host in $hosts; do
+        local cmd='for i in $(ls '${nodepath}'/err*); do echo 0 '$host' $i; nl -w 1 -s " " $i; echo; done'
+	if [ -n "$error" ]; then
+            ssh $host "$cmd" >>"$error"
+        else
+            # By default, redirect stdouts of ssh commands to stderr
+            ssh $host "$cmd" 1>&2
+        fi
+    done
+
     ####    
     # finally, clean up after ourselves
     rm -rf $jobpath
     for host in $hosts; do
-	ssh $host "rm -rf $nodepath"
+        ssh $host "rm -fr ${nodepath:?'node path isn't set''}" 
     done
     
     ####    
